on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: encoderbot.azurecr.io
        username: ${{ secrets.acr_encoderbot_username }}
        password: ${{ secrets.acr_encoderbot_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t encoderbot.azurecr.io/kmac:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push encoderbot.azurecr.io/kmac:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kmac_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep encoderbot | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace encoderbot`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: encoderbot
        container-registry-url: encoderbot.azurecr.io
        container-registry-username: ${{ secrets.acr_encoderbot_username }}
        container-registry-password: ${{ secrets.acr_encoderbot_password }}
        secret-name: kmacdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: encoderbot
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          encoderbot.azurecr.io/kmac:${{ github.sha }}
        imagepullsecrets: |
          kmacdockerauth
